### PR TITLE
replace '/deep/' with '::ng-deep'

### PR DESCRIPTION
**Pull request by ov3rk1ll**
replace '/deep/' with '::ng-deep' in scss files so it builds with angular 8

### CODE REVIEW

**Comment by yuveliremil** [comment]
When the pull request would be merged?

**Comment by stewart-southwell** [comment]
What is the hold up on this PR?

**Comment by baxter40** [comment]
Any news on the hold up on this?

**Comment by alfredott** [comment]
It was worth the wait :p
This PR was merged and is part of the 1.5.0 version released today

**Pull request merged**
