### PR TITLE
feat: add hide column configuration property

### LINKED ISSUE #1150: Hide a column in ng2-smart-table

### PR DESCRIPTION
**Pull request by eldhoseelias**
Closes #1150.

### CODE REVIEW

**Comment by eldhoseelias** [comment]
hide/show column feature is  added

**Comment by lenichols** [comment]
We need this asap

**Comment by yggg** [comment]
@eldhoseelias Thanks for your contribution! I did a few changes to the code, but it looks like you have unchecked the "Allow edits by maintainers" checkbox, so I can't push to your branch. Please, could you check this checkbox? It's on the bottom of the right sidebar:
image

**Comment by eldhoseelias** [comment]
Merge

**Review by yggg — APPROVED** [review]

**Pull request merged**
