### PR TITLE
Column checkbox select filter

### PR DESCRIPTION
**Pull request by damnko**
When adding
```
filter: {
  useEditorConfig: true
}
```
to the column configuration it will use the editor input type as column filter.
Currently works only on checkbox and select types.

Let me know if you like this approach so I will extend it to the other built-in editors.
Thanks

### CODE REVIEW

**Comment by damnko** [comment]
Sure no problem, would you like to keep the `useEditorConfig: true` possibility as well or should we go only for the custom component?

I agree on what you said, being able to use a custom component gives much more flexibility but with the drawback that you have to code your own. So I would think that being able to use the default ones could be a fast and easy-to-use solution for some users.

Let me know what you think would be the best approach. Thanks

**Comment by nnixaa** [comment]
Hi @damnko, that is not exactly what I meant :)
So the idea is to make filters configuration with exactly the same interface like the editors are now.
So that a user can do the following:

`
filter: {
  type: 'list',
  config: {
   ...
  }
}
`

or 

`
filter: {
  type: 'text',
  config: {
   ...
  }
}
`

or probably in future something like the custom editor:

`
filter: {
  type: 'custom',
  config: {
   component: ....
  }
}
`


--
Then, after that, when we have the configurable functionality, we can implement also the `userEditorConfig: true` flag, so that user won't need to duplication `config` for editor  and filter. (btw, I would rename this flag to `asEditor: true` - just a bit more concisely).

What do you think about his approach?

**Comment by damnko** [comment]
Ok everything clear now. Makes perfect sense.
Thanks for your suggestion, I will keep you posted.

**Comment by damnko** [comment]
Just one last thing: would you prefer to refactor all the editors in https://github.com/akveo/ng2-smart-table/tree/master/src/ng2-smart-table/components/cell/cell-editors to make them usable as both editors and filters or should I simply duplicate them and make them as separate components?

Even if they share some configuration I would probably separate them into independent components to keep them simpler. What do you think?

**Comment by nnixaa** [comment]
Well, good question. Let's probably separate them. Moreover, some of the editors might not have much sense as filter or have different configuration and implementation.

**Comment by youneschaoui** [comment]
this is an important feature ! when it will be merged ?

**Pull request closed without merging**
