### PR TITLE
adds checkbox type

### PR DESCRIPTION
**Pull request by vladoros**
fix for #113 
assumes you have a boolean value column, only change is checkbox type when defining it

### CODE REVIEW

**Comment by RonitBrosh** [comment]
Hi, 
tries it:
select:  {
title: 'Select',
type: 'checkbox';
},

getting text value ('true') instead of a checkbox control.
any idea?

**Comment by vladoros** [comment]
@RonitBrosh you should be able to achieve that with html column type ([example](https://github.com/akveo/ng2-smart-table/issues/58#issuecomment-256631642))
if it still doesn't render, it might have to do with angular 2 sanitization

**Comment by andreirk** [comment]
Hi,
is chekckbox type of colomn now supported? 
In docs I see comlom.type settings that can be html and editor.type  that can be checkbox
but when  I set for a colomn:

        enabled: {
          title: 'Enabled',
          filter: false,
          type: 'html',
          editor: {
            type: 'checkbox'
          }
        },

it shows just nothing in that colomn, no content.
And when I click edit, it shows my boolean value as if an input type="text"

Am I missing something?

**Comment by vladoros** [comment]
checkbox type has been [added to the latest version](https://akveo.github.io/ng2-smart-table/documentation), please use that implementation

**Pull request closed without merging**
