### PR TITLE
 fix deprecated warning, tslint fixes and fix #801 PR

### PR DESCRIPTION
**Pull request by infuse89**
fix deprecated warning, tslint fixes and fix #801 PR

### CODE REVIEW

**Comment by infuse89** [comment]
@nnixaa in previous PR i made a small mistake in table.ts, that PR fix this, and i fixed warning `It looks like you're using ngModel on the same form field as formControl.` which would result in an error in the next version of angular and automatic fixes from tslint

**Comment by nnixaa** [comment]
Hey @infuse89 this looks great, though let's distinguish the fix from lint changes, as otherwise, the commit looks a bit messy. I will release 1.3.2 right away with the fix and deprecation warning fix and then we can separately discuss lint issues - that would be awesome!

**Comment by infuse89** [comment]
@nnixaa i see you made a new release, what about the tslint?
I was based tslint fixes on this configuration https://github.com/akveo/ngx-admin/blob/master/tslint.json

**Comment by infuse89** [comment]
@nnixaa in previous verision of table.ts build with flag --prod and --aot work fine, but not working ng serve, when i make fixes for table,ts ng serve work fine, but not working build with flag --prod and --aot? maybe you can see why?

**Comment by nnixaa** [comment]
@infuse89 try 1.3.3, should work fine

**Comment by brgaulin** [comment]
@infuse89 wondering if its worth reviving part of this PR. The SelectFilter still raises deprecation warnings in the latest version of the component

**Pull request closed without merging**
