### PR TITLE
feat(datepicker): Adds datepicker editor, filter and view mode.

### LINKED ISSUE #711: Date picker in angular2 table filter
How to add date picker in angular2 smart table filter?

### PR DESCRIPTION
**Pull request by saitho**
Closes #711 and #168.

This PR adds datepicker filter, editor and display type. It uses the _ng-pick-datetime_ datepicker.

I adjusted the filter example (http://localhost:4200/#/examples/using-filters).

screen

## Configuration options
Configuration examples see AdvancedExampleFiltersComponent.

### column type: 'date' and 'shortDate'  => output is formatted using the DatePipe
(Wasn't sure about that, but needed to add it somehow... maybe there are suggestions how to deal with that better?)

### filter.type = datepicker
**Note:** for the filter to work we'll utilise the _filterFunction_ parameter. The static method _DateFilterComponent.filterFunction_ will do the filtering according to the selected date/range.

#### config.datepicker.selectMode (see "Support Range Selection" in ng-pick-datetime documentation)
* single = single date is selected (filter matches this exact date) => default
* range = a range of dates is selected (filter matches all dates that lie in this inclusive range)

### CODE REVIEW

**Comment by marticrespi** [comment]
Is this working in 1.3.5 version?

**Comment by saitho** [comment]
I just rebased onto the 1.3.5 version. Not sure about the NPM peer dependencies though, as I haven't used them yet, but it seems to work for me. :)

**Comment by marticrespi** [comment]
@saitho I think it's not included in the current version. I have tried as the example and doesn't work. In addition, the documentation doesn't explain anything about it. @akveo can you tell us something about?

Thanks!

**Comment by saitho** [comment]
@kamuran93 Just use ng2-smart-table from akveo (the original repository my changes are based on). I like its functionalities - it just doesn't have date pickers yet as my changes have not been merged. But you're able to at least add a date picker for the input fields by using a custom view renderer.
It's also available via NPM: https://www.npmjs.com/package/ng2-smart-table

**Comment by azun0214** [comment]
Hi @saitho ,

Thanks for your share, I just modify the content that you had add into ng2-smart-table, but I still cannot enable date picker in ng2-smart-table, I am waiting for the merge. thanks!

BR,
Iron.Huang

**Comment by GazousGit** [comment]
Damn, I've spent hours trying to get those change into my ng2-smart-table, now I understand that I'll have to wait for the merge :-/
Still a good work tho @saitho @akveo hope this will be merge soon :-D

**Comment by pierinho13** [comment]
Is this working in 1.4.0 version? Thanks

**Comment by saitho** [comment]
> Is this working in 1.4.0 version? Thanks

This pull request was approved but has not been merged yet. Therefore this feature is not available in 1.4.0.

However that version adds support for "custom filters", so many of my changes here might need revision. Unfortunately I'm not using smart-table anymore as I discontinued my little Angular project. Therefore I can't tell whether this pull request is still relevant for the current version or not. ^^

**Comment by savy-91** [comment]
HI, is there any plan to merge this?

**Comment by jeetendra-choudhary** [comment]
When are we going to have this available? Any plans?

**Comment by ccruza** [comment]
Any news about this feature?

**Comment by eltonlau1994** [comment]
hi all, any news about this feature?

**Comment by saitho** [comment]
This code is over 2 years old. I'm closing this PR now, sorry.
The diff should still be available if this feature may be implemented at some point in time.

In #168 someone mentioned a gist that might have worked at some point.
Maybe you can try that.

**Pull request closed without merging**
