### PR TITLE
Expanded row Feature added

### PR DESCRIPTION
**Pull request by mominsamir**
Expanded row Feature added, needed in my own project added feature, please review and merge.

### CODE REVIEW

**Comment by dj-fiorex** [comment]
Hi, i'm an user of this library, so i decided to fork it and I'll take a look at the pull requests and slowly merged everything.
If you want to help me or only support me please take a look at my [fork](https://github.com/dj-fiorex/ng2-smart-table), i will take a look at all prs and add them fast, don't worry :)
i already merged your pr!

**Comment by mominsamir** [comment]
Sure

**Comment by vamidi** [comment]
Checked the pull request in a fork of mine. First off this looks good in my opinion, but I do think you need to adjust the following. 

1. You missed to declare the `RowExpandComponent` in the module as normal- and entry component.
2. You declared a function `onExpandRowClick` inside the `ng2-smart-table` component you can remove it if there is no use for it unless I can see this as a sort of API thing.
3. You changed `ng2-smart-table` to `ngx-smart-table`. 
4. `DivViewComponent` is a great example where we can define a component where we include the table, but I think for me it would be best to narrow it down and make more strict what users can put into row in between.

Other than that good work and hopefully we see this soon in the release of `ng2-smart-table` 🚀

**Comment by mominsamir** [comment]
> Checked the pull request in a fork of mine. First off this looks good in my opinion, but I do think you need to adjust the following.
> 
> 1. You missed to declare the `RowExpandComponent` in the module as normal- and entry component.
> 2. You declared a function `onExpandRowClick` inside the `ng2-smart-table` component you can remove it if there is no use for it unless I can see this as a sort of API thing.
> 3. You changed `ng2-smart-table` to `ngx-smart-table`.
> 4. `DivViewComponent` is a great example where we can define a component where we include the table, but I think for me it would be best to narrow it down and make more strict what users can put into row in between.
> 
> Other than that good work and hopefully we see this soon in the release of `ng2-smart-table` 🚀

I have made correction, Please check and let me know,

1, fixed.
2. removed.
3. fixed now.
4. I kept this as I needed specific details for my own project, we needed to display complex component within expanded row.
5. also added couple if fixed related multi select column bug.

**Pull request closed without merging**
