### PR TITLE
Allow to add css class per row

### LINKED ISSUE #344: Allow to add class per row
Allow to add class per row in table settings.
E.g.
```
{
   rowClassFunction : function(row){
         if(row.editable) return "editable";
         return "";
   }
}
```

### PR DESCRIPTION
**Pull request by AlexShuraits**
Simply added a function that handles css class for each row in table.
fixes #344

### CODE REVIEW

**Comment by lopenchi** [comment]
When it is going to be part of the library??

**Comment by lopenchi** [comment]
Still waiting that the PR has been added :( HELP US!!!

**Comment by lexzhukov** [comment]
@AlexShuraits thanks for PR.

**Comment by valekar** [comment]
How can I use this functionality ?

**Comment by PR3M1UM** [comment]
> settings = {
        rowClassFunction: (row) => {
          if (row.cells[0].newValue === 'YAY!') {
              return 'text-success';
          } else {
              return 'text-danger';
          }
        },
        columns: {
            reactionType: {
                title: 'Type',
                filter: false,
                sort: false,
            }
        }
    };

**Comment by DependencyHell** [comment]
I would love a **cellClassFunction** :nerd_face:

**Comment by lenichols** [comment]
Be sure to put the rowClassFunction above all other settings parameters so the class settings can be mapped to the row before the row is set otherwise you will get 'undefined' in your class name which you set. I was stumped on this for hours.

**Pull request merged**
