### PR TITLE
fix create *.metadata.json when build release

### PR DESCRIPTION
**Pull request by infuse89**

### CODE REVIEW

**Comment by infuse89** [comment]
@nnixa could you review PR?

**Comment by fmpierce** [comment]
Someone please merge this... :)

**Comment by fmpierce** [comment]
How do I get this code once it's been merged? Do I need to wait for the next release?

**Comment by fmpierce** [comment]
Please release this. I need it.

**Comment by razfriman** [comment]
I agree with @fmpierce. This fixes a CRITICAL bug which renders ng2-smart-table to NOT BUILD under release mode.

**Comment by sathyakps** [comment]
Can you please release this version. Can't Build my application after upgrading to Angular 6.

**Comment by nnixaa** [comment]
Done! Sorry for the delay!

**Comment by fmpierce** [comment]
I'm still getting an error when I build on Angular6 with the --prod flag:

ERROR in : Unexpected value 'Ng2SmartTableModule ... Please add a @NgModule annotation.

Any ideas?

**Comment by infuse89** [comment]
@fmpierce try to set version 1.3.1 in this version work with flag --prod and --aot but not working ng serve and now i don now why

**Comment by fmpierce** [comment]
@infuse89 I tried that and got a different error.

**Comment by infuse89** [comment]
@fmpierce  what error on version 1.3.1?

**Comment by fmpierce** [comment]
@infuse89 
ERROR in : "let-" is only supported on ng-template elements. ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec")
: "let-" is only supported on ng-template elements. ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" let-rowz="$implicit" [ERROR ->]let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6].sec")

**Comment by infuse89** [comment]
@fmpierce this is not a smart-table module error, this is error in another module

**Comment by fmpierce** [comment]
Version 1.3.3 builds with --prod now. Thanks! 

The error I shared above was for ngx-bootstrap. Once I upgraded to version 2.0.5 it went away. Thanks for your patience.

**Pull request merged**
