### PR TITLE
Emit row data on hover.

### PR DESCRIPTION
**Pull request by vvandoorne**
We changed the tbody emitter mouseover to rowEmitter to avoid confusion with the DOM event.  Also, we needed to add an emitter to the  ng2-smart-table component to "bubble up" the row to our code.  We tested the code and we are able to get the row data in our components.

### CODE REVIEW

**Comment by bis-sb** [comment]
This was a correction to the [previous PR](https://github.com/akveo/ng2-smart-table/pull/253)

**Comment by LexZhukov** [comment]
@vvandoorne could you resolve merge conflicts?

**Comment by vvandoorne** [comment]
I’ll try to resolve those now.

**Comment by bis-sb** [comment]
Resolved -- it was just a name change to the event in the tbody component

**Pull request merged**
