### PR TITLE
export data source and pass addition parameter for ValuePrepareFunction

### PR DESCRIPTION
**Pull request by hoswey**
export data source to let user able to make custom implements and pass addition parameter row data for ValuePrepareFunction to let user display data according the row context.

### CODE REVIEW

**Comment by nnixaa** [comment]
Hi @hoswey, thanks! If you also can update this description https://github.com/akveo/ng2-smart-table/blob/master/demo/src/app/pages/documentation/documentation.html#L114 to note that these parameters are available it would be great.

**Comment by hoswey** [comment]
@nnixaa I have modified the document and add code example, pls help review.

**Comment by sielay** [comment]
+1 I even duplicated this one

**Comment by hoswey** [comment]
@nnixaa is ok for this PR?

**Comment by elviro** [comment]
@hoswey  so can this allow router links?

**Comment by hoswey** [comment]
@elviro do you means that make the table cell as a anchor link?

**Comment by elviro** [comment]
@hoswey yes.

**Pull request merged**
