### PR TITLE
Fix for issue #819

### PR DESCRIPTION
**Pull request by vsiddharthv**
Changed the 'ng2-completer' dependency package's version to 2.0.8 in order to support Angular 6

### CODE REVIEW

**Comment by nnixaa** [comment]
It's cool, thanks! The only thing - could you please revert the spacing changes so the commit only has a change of the version?

**Comment by vsiddharthv** [comment]
@nnixaa Done 👍

**Comment by Ahmad-Magdy** [comment]
Nice, I think with that we don't need rxjs-compat not anymore

**Comment by nnixaa** [comment]
@vsiddharthv we decided to move ng2-completer to peerDependencies rather than keep it as a direct library dependency. Thanks again for your help!

**Pull request closed without merging**
