### PR TITLE
Input field - specify attributes, e.g. type="date"

### PR DESCRIPTION
**Pull request by kaleguy**
I have a Chrome app I'd like to use this awesome component in. However, I want to use a date picker. Chrome supports the HTML5 "date" input type, so all I need to do is add type="date" to the input field for the proper column.

This request implements the feature of allowing the user to set arbitrary attributes, including "type" and "max" and "min" etc on the input field for a given column. I couldn't get this to work in the template so I added it to ngAfterViewInit. The important point is that the user should be able to set arbitrary attribute names, so these shouldn't be hard coded anywhere.

Demo here: https://kaleguy.github.io/ng2-smart-table-demo/
Demo requires latest Chrome or Opera to display datepicker.

### CODE REVIEW

**Comment by dan-dekel** [comment]
Will this be merged soon? Would definitely help allot - I have a similar use case.
Thanks

**Comment by cassianomon** [comment]
It will work with all the HTML input types? Like email, number and etc?

**Comment by calebeaires** [comment]
This feature will be very welcomed.

**Comment by lexzhukov** [comment]
Superseded by https://github.com/akveo/ng2-smart-table/pull/239

**Pull request closed without merging**
