### PR TITLE
Datepicker input

### PR DESCRIPTION
**Pull request by ezo5**
With raising support of input of type date [Can I Use Link](http://caniuse.com/#feat=input-datetime) I think it is good idea to add this as a separate filter without any external dependency.

### CODE REVIEW

**Comment by LexZhukov** [comment]
@ezo5 thanks for your PR. Could you resolve merge conflicts?

**Comment by charbonnier666** [comment]
Sorry.. datepicker is not active ? how make a filter in a date column ?

**Comment by ezo5** [comment]
@lexzhukov You are welcome, cant wait to stop using forked version of your project.

**Comment by madhuinwiter** [comment]
@lexzhukov Is this feature released? If yes how can I add date picker to the input..

**Comment by lexzhukov** [comment]
Closing in favour of https://github.com/akveo/ng2-smart-table/commit/993aa3a9d7c988e2d85f1c03218a0d4f674b5030

**Comment by ImenAbbes** [comment]
I want to add the datepicker to the input , so I specified attribute like this `dateDebut: {
      title: 'Date de début',
      inputAttributes: {
        type: 'date'
      }
    }` but it's not working

**Comment by madhuinwiter** [comment]
@ImenAbbes here you go..

Create a new component with the name smart-table-date-picker.component.ts and copy paste the below code.

`import { Component, AfterViewInit } from '@angular/core';

import { Cell, DefaultEditor, Editor } from 'ng2-smart-table';

@Component({
  template: `
   <input [ngClass]="inputClass"
           type="date"
           class="form-control"
           [(ngModel)]="cell.newValue"
           [name]="cell.getId()"
           [disabled]="!cell.isEditable()"
           (click)="onClick.emit($event)"
           (keydown.enter)="onEdited.emit($event)"
           (keydown.esc)="onStopEditing.emit()">
  `,
})
export class SmartTableDatePickerComponent extends DefaultEditor implements AfterViewInit {

  constructor() {
    super();
  }

  ngAfterViewInit() {

  }
}
`

Then import this compnent where ever you want. 

and in your smart table settings configure the column like below
`joined_date: {
        title: 'Joined Date',
        type: 'html',
        editor:{
          type: 'custom',
          component: SmartTableDatePickerComponent,
        }
      }`

I hope it may help you.

**Comment by ImenAbbes** [comment]
@madhuinwiter thank you , I did as you said but I when I click on the add button th add row is blank and I have this error : No component factory found for SmartTableDatePickerComponent. Did you add it to @NgModule.entryComponents?

**Comment by drsherlock** [comment]
I am getting "No component factory found for undefined. Did you add it to @NgModule.entryComponents?"

**Comment by liuhao2050** [comment]
@ImenAbbes @drsherlock I add component to entryComponents and it works.
image

**Comment by thovo** [comment]
@madhuinwiter It worked out well for me, this syntax can apply for almost other type of input, can't it? I just want to change my syntax for password and confirm password input to add in also some validation.

@ImenAbbes : avez-vous trouvé comment à résoudre votre problème?

**Comment by madhuinwiter** [comment]
@thovo Yes. It will work well for all types of inputs. Better to create new component (like date type) for your password type of input.

**Comment by sravank84** [comment]
can someone please publish there same demo working code. This would really help

**Comment by Bragegs** [comment]
My working solution as of time of writing:

1. Create directory called "smart-table-date-picker-component" inside  "src/app/@theme/components/smart-table-date-picker-component".
2. Create files "smart-table-date-picker.component.html" and "smart-table-date-picker.component.ts" inside that directory.
3. Contents of "smart-table-date-picker.components.ts": 
```
import { Component, AfterViewInit } from '@angular/core';

import { Cell, DefaultEditor, Editor } from 'ng2-smart-table';

@Component({
    templateUrl: './smart-table-date-picker.component.html',
})
export class SmartTableDatePickerComponent extends DefaultEditor implements AfterViewInit {

    constructor() {
        super();
    }

    ngAfterViewInit() {

    }
}
```
4. Contents of "smart-table-date-picker.component.html":
```
<input [ngClass]="inputClass" type="date" class="form-control" [(ngModel)]="cell.newValue" [name]="cell.getId()"
       [disabled]="!cell.isEditable()" (click)="onClick.emit($event)" (keydown.enter)="onEdited.emit($event)"
       (keydown.esc)="onStopEditing.emit()" style="height: 35px;"> 
```
5. Add the component to imports in "src/app/@theme/theme.module.ts" and to the "COMPONENT" constant:
```
import {
    FooterComponent,
    HeaderComponent,
......
    SmartTableDatePickerComponent,
......
} from './components';
.....
const COMPONENTS = [
    SwitcherComponent,
    LayoutDirectionSwitcherComponent,
    ThemeSwitcherComponent,
    HeaderComponent,
    FooterComponent,
    ThemeSettingsComponent,
......
    SmartTableDatePickerComponent,
......
];
```
6. Import the created component in the component using the smart-table:
`import {SmartTableDatePickerComponent} from '../../@theme/components'`
7. Add the component as entryComponent:
```
@Component({
    selector: 'ngx-overview',
    styleUrls: ['./overview.component.scss'],
    templateUrl: 'overview.component.html',
    entryComponents: [
        SmartTableDatePickerComponent,
    ]
})
```
8. Use custom editor to the column where you want a date-picker:
```
  settings = {
        add: {
            addButtonContent: '<i class="nb-plus"></i>',
            createButtonContent: '<i class="nb-checkmark"></i>',
            cancelButtonContent: '<i class="nb-close"></i>',
            confirmCreate: true,
        },
        edit: {
            editButtonContent: '<i class="nb-edit"></i>',
            saveButtonContent: '<i class="nb-checkmark"></i>',
            cancelButtonContent: '<i class="nb-close"></i>',
            confirmSave: true,

        },
        delete: {
            deleteButtonContent: '<i class="nb-trash"></i>',
            confirmDelete: true,
        },
        columns: {
            a_column: {
                title: 'Telefon',
                type: 'string',
                editable: false
            },
            a_date_column: {
                title: 'expiration_date',
                type: 'html',
                editor: {type: 'custom', component: SmartTableDatePickerComponent,}
            }
        },
    };
```
9. It should be working now! 
Extra info:
11. html code used:
```
<nb-card>
    <nb-card-header>
        Smart-table
    </nb-card-header>
    <nb-card-body >
        <ng2-smart-table [settings]="settings" [source]="source (editConfirm)="onEditConfirm($event)"">
        </ng2-smart-table>
    </nb-card-body>
</nb-card>
```
10. Adding example on how to transform the string from our smart-table to a Date with moment:
```
import * as moment from 'moment';

.....
    onEditConfirm(event): void {
        const new_data = event.newData;
        my_expiration_date = moment(new_data.a_date_column).toDate()
  }
.....
```
Credit to @madhuinwiter for the solution.

**Comment by azun0214** [comment]
Hi Bragegs,

that really help me!!! By the way, I follow your step and import the component then I got 1 error that shows **Uncaught (in promise): TypeError: undefined is not an object (evaluating 'modules[moduleId].call')**

Could you please help on this? thanks!


BR,
Iron.Huang

**Pull request closed without merging**
