### PR TITLE
fix(pager): fix #230

### LINKED ISSUE #230: BUG: pager not response the perPage changes
Fix suggestion

in `pager.component.ts`
```
this.source.onChanged().subscribe((changes) => {
      this.page = this.source.getPaging().page;
      this.perPage = this.source.getPaging().perPage; //add this row can fix this bug.
      this.count = this.source.count();

      if (this.isPageOutOfBounce()) {
        this.source.setPage(--this.page);
      }

      this.processPageChange(changes);
      this.initPages();
    });
}
```

Thank you.  nice plugin.

### PR DESCRIPTION
**Pull request by liaosong**
fix the #230 ,and remove unuse code.

### CODE REVIEW

**Comment by LexZhukov** [comment]
@liaosong could you resolve merge conflicts?

**Comment by liaosong** [comment]
@lexzhukov I merged the conflicts. Maybe rename file should use `git mv`.

**Comment by liaosong** [comment]
`yarn.lock` is be added to repository. why?

**Comment by lexzhukov** [comment]
@liaosong thanks. We use yarn for dependency version locking,

**Pull request merged**
