### PR TITLE
Update dependencies for: angular, rxjs, angular-cli, typescript, tslint, codelyzer

### PR DESCRIPTION
**Pull request by dimaatkaev**

### CODE REVIEW

**Comment by nnixaa** [comment]
@dimaatkaev you missed the https://github.com/akveo/ng2-smart-table/blob/master/src/ng2-smart-table/package.json I believe. Also, could you check the build isn't failing?

**Comment by lucasa** [comment]
Hi @dimaatkaev, did you fixed that?

**Comment by dimaatkaev** [comment]
Hi @lucasa, the build is ok on my local environment, but I didn't figure out what happens with Travis yet.

**Comment by aefox** [comment]
I think this can be closed since the module has been updated to angular 6

**Pull request closed without merging**
