### PR TITLE
Added checkbox column type

### PR DESCRIPTION
**Pull request by damnko**

### CODE REVIEW

**Comment by LexZhukov** [comment]
@damnko, thanks for your PR.

**Comment by nnixaa** [comment]
@damnko, @LexZhukov just thought of a situation when we have a column with boolean value by default, then we would need to configure it like this:
`
editor: {
  type: 'checkbox',
  config: {
    true: true,
    false: false
  }
}
`

which looks a bit redundantly, don't you think?

**Comment by damnko** [comment]
I think that you can simply omit `config` and it defaults to `true|false`. It should be written in the documentation too, please let me know if it does not work as expected or the doc is not clear so I act accordingly, thanks

**Comment by nnixaa** [comment]
@damnko ah sorry, missed that part (I'm a bit under the weather today :)), then we are good!

**Comment by damnko** [comment]
Eheh ok no problem

**Pull request merged**
