### PR TITLE
Add custom cell view component

### PR DESCRIPTION
**Pull request by damnko**
This should slightly improve performance and partially solve #189

### CODE REVIEW

**Comment by nnixaa** [comment]
@LexZhukov could you review this please?

**Comment by LexZhukov** [comment]
@nnixaa yes

**Comment by LexZhukov** [comment]
@damnko please, resolve the merge conflicts.

**Comment by damnko** [comment]
Done

**Comment by LexZhukov** [comment]
@damnko PR looks great! Thanks. 👍

**Pull request merged**
